<%If sett("google") = true Then%>
	<CENTER>
	<%IF Session("SiteTheme") = "a" Then%>
	<!--#include file="../images/temalar/a/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "b" Then%>
	<!--#include file="../images/temalar/b/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "c" Then%>
	<!--#include file="../images/temalar/c/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "d" Then%>
	<!--#include file="../images/temalar/d/adsense_2.asp" -->	
	<%elseIF Session("SiteTheme") = "e" Then%>
	<!--#include file="../images/temalar/e/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "f" Then%>
	<!--#include file="../images/temalar/f/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "g" Then%>
	<!--#include file="../images/temalar/g/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "h" Then%>
	<!--#include file="../images/temalar/h/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "i" Then%>
	<!--#include file="../images/temalar/i/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "j" Then%>
	<!--#include file="../images/temalar/j/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "k" Then%>
	<!--#include file="../images/temalar/k/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "l" Then%>
	<!--#include file="../images/temalar/l/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "m" Then%>
	<!--#include file="../images/temalar/m/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "n" Then%>
	<!--#include file="../images/temalar/n/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "o" Then%>
	<!--#include file="../images/temalar/o/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "p" Then%>
	<!--#include file="../images/temalar/p/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "r" Then%>
	<!--#include file="../images/temalar/r/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "s" Then%>
	<!--#include file="../images/temalar/s/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "t" Then%>
	<!--#include file="../images/temalar/t/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "u" Then%>
	<!--#include file="../images/temalar/u/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "v" Then%>
	<!--#include file="../images/temalar/v/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "y" Then%>
	<!--#include file="../images/temalar/y/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "x" Then%>
	<!--#include file="../images/temalar/x/adsense_2.asp" -->
	<%elseIF Session("SiteTheme") = "z" Then%>
	<!--#include file="../images/temalar/z/adsense_2.asp" -->
	<%End If%>
	</CENTER>
<%End If%>